### ISSUE TITLE
Using shipping to deploy cgbeacon2

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/shipping#2]
Hi!
I'd like to use this package to deploy the new beacon (https://github.com/Clinical-Genomics/cgbeacon2). Is Shipping ready to be used?

**Comment by moonso** [comment]
Yes it is being used. The problem is that we can not use it on clinical-db... But on hasta it works fine.

**Comment by northwestwitch** [comment]
Too bad, I need to deploy on clinical-db! 😞

**Comment by moonso** [comment]
I know its very frustrating. We will however abandon clinical-db very soon.

**Comment by northwestwitch** [comment]
But see, I'm open to new solutions, and not as old fashioned as you depict me! 😄
